config/routes.rb
Rails.application.routes.draw do
  get 'companies/edit', to: 'companies#edit', as: 'edit_company'
  patch 'companies/update', to: 'companies#update', as: 'update_company'

  resources :forms
  post 'forms/create_send_form_message', to: 'forms#create_send_form_message'
  get 'forms/emails_sent_by_form', to: 'forms#emails_sent_by_form'
  get 'forms/show_for_pdf/:id', to: 'forms#show_for_pdf', as: 'show_for_pdf'


  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users, :controllers => { invitations: 'users/invitations' }
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :company, dependent: :destroy
  has_many :forms, foreign_key: 'author_id', dependent: :destroy
  has_many :messages, foreign_key: 'author_id', dependent: :destroy

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  scope :by_company, ->(company_id) { where("company_id = ?", company_id) }

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  def invitation_status
    if self.invitation_accepted_at
      return "Invitation acceptée le #{self.invitation_accepted_at.strftime('%d/%m/%Y')}"
    else
      return "Invitation pas encore acceptée"
    end
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController


  # POST /resource/invitation
  def create
   self.resource = invite_resource
   
   resource_invited = resource.errors.empty?


   yield resource if block_given?

   if resource_invited
     if is_flashing_format? && self.resource.invitation_sent_at
       set_flash_message :notice, :send_instructions, :email => self.resource.email
     end
     @users = User.all
   else
     respond_with_navigational(resource) { render :new }
   end
  end

  private
        def invite_resource
            resource_class.invite!(invite_params, current_inviter) do |invitable|
                invitable.company_id = current_user.company_id
            end
        end


 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    @user = User.new
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  def create_invitation
    @user = User.new(new_invitation_params)
    @user.invited_by_id = current_user.id
    @user.invitation_created_at = Date.new
    @user.invitation_token = 'token' #todo generate token
  
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

  def new_invitation_params
    params.require(:user).permit(:email)
  end

end

app/views/users/_new_invitation.html.erb
<%= form_for @user, url: user_invitation_path, remote: true do |f| %>
  <h3>Invitation</h3>
<div class="form-group">
  <div class="form-group">
    <%= f.label :email, 'Email' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <%= f.submit 'Envoyer', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/users/_users.html.erb
<% @users.each do |user| %>
  <tr>
    <td>
      <%= link_to user.email, user %>
    </td>
    <td>
      <%= user.invitation_status %>
    </td>
    <td>
      <%= form_for(user) do |f| %>
        <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
        <%= f.submit 'Changer de role', :class => 'button-xs' %>
      <% end %>
    </td>
    <td>
      <%= link_to("Supprimer", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
    </td>
  </tr>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header">Utilisateurs
              <small></small>
          </h1>
      </div>
  </div>
  <div class="row">
    <div class="col-md-9">
      <table class="table">
        <thead>
          <tr>
            <th>Email</th>
            <th>Invitation</th>
            <th>Role</th>
          </tr>
        </thead>
        <tbody id="users">
          <%= render 'users' %>
        </tbody>
      </table>
    </div>
    <div class="col-md-3">
      <%= render 'new_invitation' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>