config/routes.rb
Rails.application.routes.draw do
  get 'companies/edit', to: 'companies#edit', as: 'edit_company'
  patch 'companies/update', to: 'companies#update', as: 'update_company'

  resources :forms
  post 'forms/create_send_form_message', to: 'forms#create_send_form_message'
  get 'forms/emails_sent_by_form', to: 'forms#emails_sent_by_form'
  get 'forms/show_for_pdf/:id', to: 'forms#show_for_pdf', as: 'show_for_pdf'


  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users, :controllers => { invitations: 'users/invitations' }
  resources :users
end

app/models/form_type.rb
class FormType < ApplicationRecord
  has_many :forms
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :create_send_form_message, :show_for_pdf]

  def index
    @forms = Form.all.by_company(current_user.company_id)
    @form = Form.new
    @types = FormType.all
  end

  def show
    @form = Form.find_by_uid(params[:id])
    @message = Message.new
    @messages = Message.by_form(@form.id)
    @company = @form.company

    respond_to do |format|
      format.html do
        if (params[:as_pdf])
          render "forms/templates/#{@form.type.filename}_pdf",
                 :layout => "application_pdf.html.erb"
        else
          render "forms/templates/#{@form.type.filename}"
        end
      end
      format.pdf do
        options = {
          title: @form.type.label,
          header: {
            font_size: 8,
            left: Time.now.strftime("%d-%m-%Y"),
            center: "#{@form.company.name}",
            right: '[page] / [topage]'
          },

          footer: {
            font_size: 8,
            center: "#{@form.company.number} #{@form.company.street} #{@form.company.zip} #{@form.company.city} - #{@form.company.phone}"
          }
          #
          # footer: {
          #   html: {
          #     template:'templates/footer.html.erb'
          #   }
          # }
        }

        data = WickedPdf.new.pdf_from_url(show_for_pdf_url(@form.uid), options)
        send_data( data, :filename => "#{@form.type.label}.pdf" )
        #render :pdf => "file_name",
        #        :template => "forms/templates/#{@form.type.filename}",
        #        :layout => "application_pdf.html.erb",
        #        :javascript_delay => 2000
      end
    end
  end

  def show_for_pdf
    @form = Form.find_by_uid(params[:id])
    res = FirebaseRef.get "/forms/#{@form.uid}"
    @data = res.body.to_json
    render "forms/templates/#{@form.type.filename}_pdf",
           layout: "application_pdf.html.erb"
  end

  def new
    @form = Form.new
    @types = FormType.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @form = Form.new(form_params)

    @form.author_id = current_user.id
    @form.company_id = current_user.company_id
    new_firebase_form_key = FirebaseRef.push('forms', {'meta': { 'company_id': @form.company_id} }) # generate new firebase key (form.uid) under /forms path
    @form.uid = new_firebase_form_key.body['name'] # assign key as uid form
    #@form.uid = '98934j3493434jk43s' + Date.new().to_s

    if @form.save
      redirect_to form_url(@form.uid) # redirect to show screen
    else
      @types = FormType.all
      render :new
    end
  end

  def create_send_form_message
    @message = Message.new(message_params)
    @message.author_id = current_user.id
    @message.save
    @messages = Message.by_form(@message.form_id)


    FormMailer.send_form_email(@message).deliver_later
  end

  # def emails_sent_by_form
  #   @messages = Message.by_form(params[:form_id])
  # end

  private

     # Never trust parameters from the scary internet, only allow the white list through.
     def form_params
       params.require(:form).permit(:type_id, :email, :message)
     end

     def message_params
       params.require(:message).permit(:to, :content, :form_id, :form_as_pdf)
     end

end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_contact.html.erb
<h3>Contact Details</h3>
<p>
    3481 Melrose Place<br>Beverly Hills, CA 90210<br>
</p>
<p><i class="fa fa-phone"></i>
    <abbr title="Phone">P</abbr>: (123) 456-7890</p>
<p><i class="fa fa-envelope-o"></i>
    <abbr title="Email">E</abbr>: <a href="mailto:name@example.com">name@example.com</a>
</p>
<p><i class="fa fa-clock-o"></i>
    <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM</p>
<ul class="list-unstyled list-inline list-social-icons">
    <li>
        <a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
    </li>
    <li>
        <a href="#"><i class="fa fa-linkedin-square fa-2x"></i></a>
    </li>
    <li>
        <a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
    </li>
    <li>
        <a href="#"><i class="fa fa-google-plus-square fa-2x"></i></a>
    </li>
</ul>

app/views/forms/_export_to_pdf.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Export PDF</div>
  <div class="panel-body">
    <%= link_to form_path(@form, format: :pdf) do %>
      <i class="fa fa-file-pdf-o"></i> <%= @form.type.label %>.pdf
    <% end %>
  </div>
</div>

app/views/forms/_form_aside.html.erb
<% if user_signed_in? %>
  <%= render 'export_to_pdf' %>
<% end %>
<%= render 'send_by_email_new' %>
<% unless user_signed_in? %>
  <%= render 'companies/contact' %>
<% end %>
<% if user_signed_in? %>
  <%= render 'meta' %>
<% end %>

app/views/forms/_forms.html.erb
<% @forms.each do |form| %>
  <tr>
    <td><%= form.author.email %></td>
    <td><%= form.type.label %></td>
    <td><%= link_to "Show", form %></td>
    <td><%= link_to "Remove", form, method: :delete, data: { confirm: "Are you sure?" } %></td>
  </tr>
<% end %>

app/views/forms/_message.erb
<tr><td><em><%= message.to %></td><td alt="<%= message.created_at.strftime("%d/%m/%Y %H:%M") %>"><%= message.created_at.strftime("%d/%m/%Y") %></td></tr>

app/views/forms/_messages.erb
<% if @messages.size > 0 %>
  <table class="table" id="emails_sent">
    <thead>
      <tr>
        <th>Envoyé à</th>
        <th>le</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'message', collection: @messages %>
    </tbody>
  </table>
<% end %>

app/views/forms/_meta.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Détails</div>
  <div class="panel-body">
    <div class="list-group">
      <a href="#" class="list-group-item">
          Création
          <span class="pull-right text-muted small"><em><%= @form.created_at %></em>
          </span>
      </a>
      <a href="#" class="list-group-item">
          Dernière mise à jour
          <span class="pull-right text-muted small"><em><%= @form.created_at %></em>
          </span>
      </a>
      <a href="#" class="list-group-item">
          Auteur
          <span class="pull-right text-muted small"><em>Denis Jacquemin</em>
          </span>
      </a>
  </div>
  </div>
</div>

app/views/forms/_new.html.erb
<%= form_for(@form) do |f| %>
  <h3>Nouveau formulaire</h3>
  <div class="form-group">
    <%= f.collection_select :type_id, @types, :id, :label, {}, class: 'form-control' %>
  </div>
  <%= f.submit 'Création', class: 'btn btn-primary' %>
<% end %>

app/views/forms/_send_by_email_new.html.erb
<% if user_signed_in? %>
  <div class="panel panel-default">
    <div class="panel-heading">Envoyer ce formulaire</div>
    <div class="panel-body">
      <%= form_for @message, url: {action: "create_send_form_message"}, remote: true do |f| %>
        <%= f.hidden_field :form_id, value: @form.id%>
        <div class="form-group">
          <div class="row">
              <div class="col-md-6"><%= f.label :to, 'Email' %></div>
              <!--<div class="col-md-6 text-right"><%= link_to 'client' %> | <%= link_to 'backoffice' %></div>-->
          </div>
          <%= f.text_field :to, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :content, 'Message' %>
          <%= f.text_area :content, class: 'form-control', rows: '8' %>
        </div>
        <div class="checkbox">
          <label>
            <%= f.check_box :form_as_pdf %> Joindre le formulaire en pdf
          </label>
        </div>
        <%= f.submit 'Envoyer', class: 'btn btn-primary btn-block' %>
      <% end %>
      <%= render 'messages' %>
    </div>
  </div>
<% else %>
  <div class="panel panel-default">
    <div class="panel-heading">Envoyer ce formulaire</div>
    <div class="panel-body">
      <%= form_for @message, url: {action: "create_send_form_message"}, remote: true do |f| %>
        <%= f.hidden_field :form_id, value: @form.id%>
        <%= f.hidden_field :to, value: @form.author.email %>
        <div class="form-group">
          <%= f.label :content, 'Remarques' %>
          <%= f.text_area :content, class: 'form-control', rows: '8' %>
        </div>
        <%= f.submit 'Envoyer', class: 'btn btn-primary btn-block' %>
        <%= render 'messages' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/forms/create_send_form_message.js.erb
$('#new_message')[0].reset();
$('#emails_sent').html("<%= j (render 'messages', locals: {messages: @messages}) %>");

app/views/forms/index.html.erb
<div class="container">
  <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header"><%= t 'forms.index.list_of_forms' %>
              <small></small>
          </h1>
      </div>
  </div>
  <div class="row">
    <div class="col-md-9">
      <table class="table">
        <thead>
          <tr>
            <th>Auteur</th>
            <th>Type</th>
            <th>Status</th>
            <th>Client</th>
            <th>Date de création</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody id="forms">
          <%= render "forms" %>
        </tbody>
      </table>
    </div>
    <div class="col-md-3">
      <%= render 'new' %>
    </div>
  </div>